stages:
  - syntax-check
  - lint
  - unit-test
  - report
  - deploy

syntax-check:
  stage: syntax-check
  image: rust:latest
  script:
    - cargo rustc -- -D warnings

fmt:
  stage: lint
  needs: ["syntax-check"]
  image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo fmt --check

test-default:
  stage: unit-test
  needs: ["fmt"]
  image: rust:latest
  script:
    - cargo test

test-native:
  stage: unit-test
  needs: ["fmt"]
  image: rust:latest
  script:
    - cargo test --no-default-features --features native

test-serde:
  stage: unit-test
  needs: ["fmt"]
  image: rust:latest
  script:
    - cargo test --no-default-features --features "native serde-serialize"

test-openblas:
  stage: unit-test
  needs: ["fmt"]
  image: rust:latest
  script:
    - cargo test --no-default-features --features openblas

.test-netlib:
  stage: unit-test
  needs: ["fmt"]
  image: rust:latest
  script:
    - cargo test --no-default-features --features netlib

.test-intelmkl:
  stage: unit-test
  needs: ["fmt"]
  image: rust:latest
  script:
    - cargo test --no-default-features --features intel-mkl

test-convert-mint:
  stage: unit-test
  needs: ["fmt"]
  image: rust:latest
  script:
    - cargo test --no-default-features --features "native mint"


